name: odometer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  #Secure
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  #State management
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  get_it: ^7.6.7
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  auto_route: 8.0.3
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0
  shimmer: ^3.0.0
  device_info_plus: ^10.1.0
  path_provider: ^2.1.2
  applovin_max: ^3.8.1
  upgrader: ^10.0.0
  permission_handler: ^11.3.0
  in_app_review: ^2.0.8
  animated_bottom_navigation_bar: ^1.3.3
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  location: ^6.0.2
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  rxdart: ^0.28.0
  flutter_local_notifications: ^17.2.2
  map_launcher: ^3.4.0
  sleek_circular_slider: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_animate: ^4.5.0
  flutter_compass: ^0.8.0
  carousel_slider: ^5.0.0
  flutter_hooks: ^0.20.3
  geolocator: ^12.0.0
  equatable: 2.0.5
  cached_network_image: ^3.4.0
  overlay_support: ^2.1.0
  open_settings_plus: ^0.3.3
  fluttertoast: ^8.2.8
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.1
  json_serializable: ^6.7.1
  build_runner:
  injectable_generator: ^2.6.1
  auto_route_generator:
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo/logo.png
    - assets/icons/
    - assets/icons/rates/
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/languages/
    - assets/images/odometer/
    - assets/images/odometer/theme0/
    - assets/images/odometer/theme1/
    - assets/images/odometer/theme2/
    # - assets/images/odometer/theme3/
    - assets/images/odometer/theme4/
    - assets/images/odometer/theme5/
    - assets/images/odometer/theme6/
    - assets/images/premium/
    - assets/icons/permission/
    - assets/icons/tabbar/
    - assets/icons/dialog/
    - assets/icons/map/
    - assets/icons/settings/
    - assets/images/map/
    - assets/icons/trip/
    - assets/icons/weather/

  fonts:
    - family: sfpro
      fonts:
        - asset: assets/fonts/sfpro/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/sfpro/SF-Pro-Display-Light.otf
          weight: 200
        - asset: assets/fonts/sfpro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sfpro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sfpro/SF-Pro-Display-SemiBold.otf
          weight: 600
        - asset: assets/fonts/sfpro/SF-Pro-Display-Bold.otf
          weight: 700
    - family: dsdigi
      fonts:
        - asset: assets/fonts/ds_digi/ds-digithin.ttf
          weight: 400
        - asset: assets/fonts/ds_digi/ds-digibold.ttf
          weight: 700

#generate
flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: MyColors

  assets:
    outputs:
      class_name: Assets
